### ISSUE TITLE
I am not able to install arcode on R-4.1.0

### ISSUE THREAD

**Issue by IshaMonga** [ConesaLab/acorde#2]
["ConesaLab/acorde"](pkgbuild::with_build_tools(install.packages("ConesaLab/acorde", type = "source")))

Warning in install.packages :
  package ‘ConesaLab/acorde’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages

**Comment by aarzalluz** [comment]
Hi @IshaMonga,

I see that you are trying to install via CRAN using `install.packages()`. However, acorde needs to be installed directly from GitHub. Please see the [installation section in the README](https://github.com/ConesaLab/acorde#installation).

Ángeles

**Comment by IshaMonga** [comment]
Thank you. 
I tried that too..!!

Here is the error I received:

> devtools::install_github("ConesaLab/acorde")

Downloading GitHub repo ConesaLab/acorde@HEAD
Downloading GitHub repo skinnider/dismay@HEAD
Skipping 5 packages not available: AnnotationDbi, GO.db, preprocessCore, impute, propr
✔  checking for file ‘/private/var/folders/wx/vjktgsz94msfjz3ds179gq4m0000gn/T/RtmpdVdzMV/remotescf195c3eba83/skinnider-dismay-4a0ad33/DESCRIPTION’ (621ms)
─  preparing ‘dismay’:
✔  checking DESCRIPTION meta-information ...
─  installing the package to process help pages
         -----------------------------------
   ERROR: dependency ‘propr’ is not available for package ‘dismay’
─  removing ‘/private/var/folders/wx/vjktgsz94msfjz3ds179gq4m0000gn/T/RtmpyFHQdc/Rinste49f5a2bd1e2/dismay’
         -----------------------------------
   ERROR: package installation failed
Error: Failed to install 'acorde' from GitHub:
  Failed to install 'dismay' from GitHub:
  ! System command 'R' failed

**Comment by aarzalluz** [comment]
@IshaMonga -seems to be an issue with [dismay](https://github.com/skinnider/dismay) dependency [propr](https://github.com/cran/propr). Perhaps you could try to install both propr and dismay from GitHub (info available at the links), then run the installation command for acorde again?

**Comment by IshaMonga** [comment]
Thank you. I have installed acorde..!!
