### ISSUE TITLE
Tutorial error: zinbwave weight computation fails for genes with all-zero counts

### ISSUE THREAD

**Issue by IshaMonga** [ConesaLab/acorde#3]
sce <- zinbwave(sce, observationalWeights = TRUE, 
                BPPARAM = MulticoreParam(6))

Error in zinbInitialize(m, Y, nb.repeat = nb.repeat.initialize, BPPARAM = BPPARAM) : 
  Gene 322 has only 0 counts!

**Comment by aarzalluz** [comment]
Hi @IshaMonga,

When opening an issue, pease include a full description of your problem as well as a meaningful title -it will make it easier for developers to understand the issue and provide help :)

Regarding your post, it seems that some of the genes in your SCE object have only zero counts. I suggest you try a more stringent filtering strategy at the stage of quality control before using the acorde pipeline. You are welcome to use some of the options provided within acorde (see section 5.1 in the main vignette for details).

I hope that helps,

Ángeles
